kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: disk-ssd-test4
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: alicloud-disk-available
  resources:
    requests:
      storage: 20Gi
