apiVersion: apps/v1 
kind: Deployment
metadata:
  name: monapi
spec:
  selector:
    matchLabels:
      app: monapi
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: monapi
    spec:
      containers:
      - image: monitor-registry.cn-beijing.cr.aliyuncs.com/dev/tools:collector
        name: collector
        ports:
        - name: collector-http
          containerPort: 2058
        resources:
          requests:
            memory: "512Mi" 
        volumeMounts:
          - name: address
            mountPath: /n9e/etc/address.yml
            subPath: address.yml
          - name: collector
            mountPath: /n9e/etc/collector.yml
            subPath: collector.yml

      - image: monitor-registry.cn-beijing.cr.aliyuncs.com/dev/tools:monapi
        name: monapi
        ports:
        - name: monapi-http
          containerPort: 5800
        volumeMounts:
          - name: address
            mountPath: /n9e/etc/address.yml
            subPath: address.yml
          - name: monapi
            mountPath: /n9e/etc/monapi.yml
            subPath: monapi.yml
          - name: mysql
            mountPath: /n9e/etc/mysql.yml
            subPath: mysql.yml
        resources:
          requests:
            memory: "512Mi"
      volumes:
        - name: address
          configMap:
            name: address-config
        - name: monapi 
          configMap:
            name: monapi-config
        - name: mysql
          configMap:
            name: mysql-config
        - name:  collector
          configMap:
            name: collector-config

---
apiVersion: v1
kind: Service
metadata:
  name: monapi-svc
  labels:
    app: monapi
spec:
  ports:
  - port: 5800
    name: monapi-http
  clusterIP: None
  selector:
    app: monapi
