apiVersion: v1
data:
  mysql.yml: |
    ---
    uic:
      addr: "root:123456@tcp(mysql-0.mysql-svc:3306)/n9e_uic?charset=utf8&parseTime=True&loc=Asia%2FShanghai"
      max: 16
      idle: 4
      debug: false
    mon:
      addr: "root:123456@tcp(mysql-0.mysql-svc:3306)/n9e_mon?charset=utf8&parseTime=True&loc=Asia%2FShanghai"
      max: 16
      idle: 4
      debug: false
    hbs:
      addr: "root:123456@tcp(mysql-0.mysql-svc:3306)/n9e_hbs?charset=utf8&parseTime=True&loc=Asia%2FShanghai"
      max: 16
      idle: 4
      debug: false
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mysql-config
  selfLink: /api/v1/namespaces/default/configmaps/mysql-config
