apiVersion: apps/v1 
kind: Deployment
metadata:
  name: transfer
spec:
  selector:
    matchLabels:
      app: transfer
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: transfer
    spec:
      containers:
      - image: monitor-registry.cn-beijing.cr.aliyuncs.com/dev/tools:transfer
        name: transfer
        ports:
        - name: transfer-http
          containerPort: 5810
        - name: transfer-rpc
          containerPort: 5811
        volumeMounts:
          - name: address
            mountPath: /n9e/etc/address.yml
            subPath: address.yml
          - name: transfer
            mountPath: /n9e/etc/transfer.yml
            subPath: transfer.yml
        resources:
          limits:
            cpu: "1"
            memory: "1024Mi"
          requests:
            memory: "512Mi"
      - image: monitor-registry.cn-beijing.cr.aliyuncs.com/dev/tools:collector
        name: collector
        ports:
        - name: collector-http
          containerPort: 2058
        resources:
          limits:
            cpu: "1"
            memory: "1024Mi"
          requests:
            memory: "512Mi" 
        volumeMounts:
          - name: address
            mountPath: /n9e/etc/address.yml
            subPath: address.yml
          - name: collector
            mountPath: /n9e/etc/collector.yml
            subPath: collector.yml

      volumes:
        - name: address
          configMap:
            name: address-config
        - name:  transfer
          configMap:
            name: transfer-config
        - name:  collector
          configMap:
            name: collector-config

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-address-type: "intranet"
  name: transfer-svc
  labels:
    app: transfer
spec:
  ports:
  - port: 5810
    name: transfer-http
    protocol: TCP
  - port: 5811
    name: transfer-rpc
    protocol: TCP
  #clusterIP: None
  type: LoadBalancer
  selector:
    app: transfer
