apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tsdb
  namespace: default
spec:
  selector:
    matchLabels:
      app: tsdb # has to match .spec.template.metadata.labels
  serviceName: "tsdb-svc"
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        app: tsdb # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: tsdb
        image: monitor-registry.cn-beijing.cr.aliyuncs.com/dev/tools:tsdb
        ports:
        - name: tsdb-http
          containerPort: 5820
        - name: tsdb-rpc
          containerPort: 5821
        volumeMounts:
        - name: ssd-data
          mountPath: /n9e/data
  volumeClaimTemplates:
  - metadata:
      name: ssd-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "alicloud-disk-available"
      resources:
        requests:
          storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: tsdb-svc
  labels:
    app: tsdb
spec:
  ports:
  - port: 5820
    name: tsdb-http
  - port: 5821
    name: tsdb-rpc
  clusterIP: None
  selector:
    app: tsdb
